// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgAddDistributor } from "./types/entangle/distributorsauth/tx";
import { MsgAddAdmin } from "./types/entangle/distributorsauth/tx";
import { MsgRemoveDistributor } from "./types/entangle/distributorsauth/tx";
import { MsgRemoveAdmin } from "./types/entangle/distributorsauth/tx";


export { MsgAddDistributor, MsgAddAdmin, MsgRemoveDistributor, MsgRemoveAdmin };

type sendMsgAddDistributorParams = {
  value: MsgAddDistributor,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddAdminParams = {
  value: MsgAddAdmin,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveDistributorParams = {
  value: MsgRemoveDistributor,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveAdminParams = {
  value: MsgRemoveAdmin,
  fee?: StdFee,
  memo?: string
};


type msgAddDistributorParams = {
  value: MsgAddDistributor,
};

type msgAddAdminParams = {
  value: MsgAddAdmin,
};

type msgRemoveDistributorParams = {
  value: MsgRemoveDistributor,
};

type msgRemoveAdminParams = {
  value: MsgRemoveAdmin,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgAddDistributor({ value, fee, memo }: sendMsgAddDistributorParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddDistributor: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddDistributor({ value: MsgAddDistributor.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddDistributor: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddAdmin({ value, fee, memo }: sendMsgAddAdminParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddAdmin: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddAdmin({ value: MsgAddAdmin.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddAdmin: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveDistributor({ value, fee, memo }: sendMsgRemoveDistributorParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveDistributor: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveDistributor({ value: MsgRemoveDistributor.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveDistributor: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveAdmin({ value, fee, memo }: sendMsgRemoveAdminParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveAdmin: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveAdmin({ value: MsgRemoveAdmin.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveAdmin: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgAddDistributor({ value }: msgAddDistributorParams): EncodeObject {
			try {
				return { typeUrl: "/entangle.distributorsauth.MsgAddDistributor", value: MsgAddDistributor.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddDistributor: Could not create message: ' + e.message)
			}
		},
		
		msgAddAdmin({ value }: msgAddAdminParams): EncodeObject {
			try {
				return { typeUrl: "/entangle.distributorsauth.MsgAddAdmin", value: MsgAddAdmin.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddAdmin: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveDistributor({ value }: msgRemoveDistributorParams): EncodeObject {
			try {
				return { typeUrl: "/entangle.distributorsauth.MsgRemoveDistributor", value: MsgRemoveDistributor.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveDistributor: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveAdmin({ value }: msgRemoveAdminParams): EncodeObject {
			try {
				return { typeUrl: "/entangle.distributorsauth.MsgRemoveAdmin", value: MsgRemoveAdmin.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveAdmin: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			EntangleDistributorsauth: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;